lang: "en"

title: "Ayan Mandal"
description: "Ayan Mandal’s Developer Portfolio."
tagline: "A showcase of my Python projects, web apps, games, technical blogs, and hands-on experience in coding and technology development."
url: "https://CodeCraftAyan.github.io"
baseurl: "/Ayan-Mandal"

keywords: ["Tailwindcss", "Javascript", "Python", "Django", "Flask", "API", "Software Engineering", "Web Development", "AI", "Machine Learning", "Portfolio", "Coding Projects"]

author:
  name: "Ayan Mandal"
  email: "ayan.mandal.work@gmail.com"
  github: "CodeCraftAyan"

logo: /assets/image/base/preview.png
image: /assets/image/base/preview.png

social:
  name: "Ayan Mandal"
  links:
    - https://github.com/CodeCraftAyan

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  pages:
    output: true
  blog:
    output: true
    permalink: /blogs/:title/
  experience:
    output: true
    permalink: /experience/:title/

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"

seo:
  canonical: true

webmaster_verifications:
  google: "pXFb89g-h3cP4d_VWRPw6Q3B7stBGj5KTh5usqA_avg"