title: "Ayan Mandal"
description: "The official portfolio of Ayan Mandal, showcasing software projects, technical blogs, and experience in coding and development."
url: "https://CodeCraftAyan.github.io"
baseurl: "/ayan-mandal"

author:
  name: "Ayan Mandal"
  email: "ayan.mandal.work@gmail.com"
  github: "CodeCraftAyan"

logo: "/assets/image/favicon.ico"
image: "/assets/image/base/preview.jpg" 

social:
  name: "Ayan Mandal"
  links:
    - https://github.com/CodeCraftAyan

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
  blog:
    output: true
    permalink: /blogs/:title/
  experience:
    output: true
    permalink: /experience/:title/

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"